---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      # - recipe[aws::default]
      - recipe[esor_search::default]
    attributes:
      ec2:
        placement_availability_zone: us-west-1b
