---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[esor_search_test::default]
    attributes:
      esor:
        source: amazon
      ec2:
        placement_availability_zone: us-west-1b
  - name: gcloud
    run_list:
      - recipe[esor_search_test::default]
    attributes:
      esor:
        source: gcloud