name 'esor_search'
maintainer 'Darren Foo'
maintainer_email 'stonith@users.noreply.github.com'
license 'mit'
description 'Installs/Configures esor_search'
long_description 'Installs/Configures esor_search'
version '0.1.0'
